const fs = require('fs');
let code = fs.readFileSync('src/utils/audio.ts', 'utf8');

code = code.replace(/PolyglotScribe Export/g, 'Multilingual Scribe Export');
code = code.replace(/<h1>PolyglotScribe Document<\/h1>/g, '<h1>Multilingual Scribe Document</h1>');
code = code.replace(/Generated by PolyglotScribe/g, 'Generated by Multilingual Scribe');
code = code.replace(/doc\.text\("PolyglotScribe", 40, 50\);/g, 'doc.text("Multilingual Scribe", 40, 50);');
code = code.replace(/Exported via PolyglotScribe/g, 'Exported via Multilingual Scribe');

fs.writeFileSync('src/utils/audio.ts', code);
