import { jsPDF } from 'jspdf';

/**
 * Formats raw 16-bit mono PCM bytes into a standard playable RIFF WAV Blob
 */
export function pcmToWavBlob(pcmBase64: string, sampleRate = 24000): Blob {
  const binaryString = atob(pcmBase64);
  const len = binaryString.length;
  const buffer = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    buffer[i] = binaryString.charCodeAt(i);
  }
  const wavHeader = new ArrayBuffer(44);
  const view = new DataView(wavHeader);

  // "RIFF" chunk descriptor
  view.setUint32(0, 0x52494646, false);
  // Total file size minus 8 bytes RIFF header
  view.setUint32(4, 36 + buffer.length, true);
  // "WAVE" format
  view.setUint32(8, 0x57415645, false);
  // "fmt " subchunk
  view.setUint32(12, 0x666d7420, false);
  // Subchunk1Size (16 for PCM)
  view.setUint32(16, 16, true);
  // AudioFormat (1 for PCM)
  view.setUint16(20, 1, true);
  // NumChannels (1 = mono)
  view.setUint16(22, 1, true);
  // SampleRate
  view.setUint32(24, sampleRate, true);
  // ByteRate = SampleRate * NumChannels * BitsPerSample/8
  view.setUint32(28, sampleRate * 2, true);
  // BlockAlign = NumChannels * BitsPerSample/8
  view.setUint16(32, 2, true);
  // BitsPerSample
  view.setUint16(34, 16, true);
  // "data" subchunk
  view.setUint32(36, 0x64617461, false);
  // Subchunk2Size
  view.setUint32(40, buffer.length, true);

  return new Blob([wavHeader, buffer], { type: 'audio/wav' });
}

/**
 * Exports text content as a formatted Microsoft Word document (.doc)
 */
export function exportToWord(text: string, fileName = 'transcription.doc'): void {
  if (!text) return;
  const header = `<!DOCTYPE html><html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40"><head>
  <meta charset="utf-8">
  <title>Multilingual Scribe Export</title>
  <style>
    body { font-family: 'Calibri', 'Segoe UI', Tahoma, sans-serif; font-size: 13pt; line-height: 1.6; color: #1e293b; padding: 20pt; }
    h1 { color: #4338ca; font-size: 18pt; border-bottom: 2pt solid #e2e8f0; padding-bottom: 6pt; margin-bottom: 16pt; }
    .content { white-space: pre-wrap; }
    .footer { margin-top: 30pt; font-size: 9pt; color: #64748b; border-top: 1pt solid #e2e8f0; padding-top: 6pt; }
  </style></head><body>
  <h1>Multilingual Scribe Document</h1>
  <div class="content">${text.replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\n/g, '<br/>')}</div>
  <div class="footer">Generated by Multilingual Scribe • Horn of Africa Speech Dictator & Voice Synthesis</div></body></html>`;

  const blob = new Blob(['\ufeff', header], { type: 'application/msword;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Exports text content to PDF using jsPDF
 */
export function exportToPDF(text: string, fileName = 'transcription.pdf', onDone?: () => void): void {
  if (!text) return;
  
  try {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'pt',
      format: 'letter'
    });
    
    // Title
    doc.setFontSize(18);
    doc.setTextColor(67, 56, 202); // Indigo 700
    doc.text("Multilingual Scribe", 40, 50);
    
    // Subtitle
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); // Slate 500
    doc.text("Horn of Africa Speech & Voice Document", 40, 65);
    
    // Date
    doc.text(new Date().toLocaleDateString(), 500, 50);
    
    // Line separator
    doc.setDrawColor(226, 232, 240); // Slate 200
    doc.setLineWidth(2);
    doc.line(40, 75, 570, 75);
    
    // Body Text
    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59); // Slate 800
    
    // Split text into lines that fit the page width
    const splitText = doc.splitTextToSize(text, 530);
    
    // Pagination logic
    let y = 100;
    const pageHeight = doc.internal.pageSize.getHeight();
    
    for (let i = 0; i < splitText.length; i++) {
      if (y > pageHeight - 60) {
        doc.addPage();
        y = 50;
      }
      doc.text(splitText[i], 40, y);
      y += 18;
    }
    
    // Footer
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184); // Slate 400
    doc.text("Exported via Multilingual Scribe", 40, pageHeight - 30);
    
    doc.save(fileName);
    if (onDone) onDone();
  } catch (err) {
    console.error("PDF Export failed:", err);
    // Fallback to print
    window.print();
    if (onDone) onDone();
  }
}
